{
 "title": "云防火墙(CFW)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "$EPS:防护带宽使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_used_protection_bandwidth{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:防护带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_protection_bandwidth_usage{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:VPC间防护带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_vpc_protection_bandwidth_usage_rate{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:VPC间防护带宽使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_vpc_protection_bandwidth_usage{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:ACL规则命中次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_acl_hit_count{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:ACL规则阻断次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_acl_deny_count{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:防火墙VPC间pps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_vpc_protection_pps{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:IPS规则阻断次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_ips_deny_count{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:防火墙互联网方向pps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_pps{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:IPS规则命中次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_ips_hit_count{ep_id=\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:互联网防护带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_bandwidth_usage_rate{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:互联网防护带宽使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cfw_internet_protection_bandwidth_usage{ep_id=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}