{
 "title": "云专线(DCAAS)",
 "description": "【华为云DCASS支持的监控指标】https://support.huaweicloud.com/usermanual-dc/dc_04_0802.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "专线IP",
    "query": {
     "query": "label_values(huaweicloud_sys_dcaas_network_incoming_bytes{epId=~\"$EPS\"},device_id)"
    }
   },
   {
    "name": "hostname",
    "label": "专线名称",
    "query": {
     "query": "label_values(huaweicloud_sys_dcaas_network_incoming_bytes{epId=~\"$EPS\",device_id=~\"$hostIP\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源总览-华为云专线", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云专线资源总览表",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_bits_rate{} - 0",
     "legendFormat": "网络流入带宽"
    },
    {
     "expr": "huaweicloud_sys_dcaas_network_outgoing_bits_rate{} - 0",
     "legendFormat": "网络流出带宽"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_incoming_bytes{}) by (name) - 0",
     "legendFormat": "网络流入流量"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_outgoing_bytes{}) by (name) - 0",
     "legendFormat": "网络流出流量"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_incoming_packets_rate{}) by (name) - 0",
     "legendFormat": "网络流入包速率"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_outgoing_packets_rate{}) by (name) - 0",
     "legendFormat": "网络流出包速率"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_latency{}) by (name) - 0",
     "legendFormat": "时延"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_packet_loss_rate{}) by (name) -0",
     "legendFormat": "丢包率"
    }
   ]
  },
  {
   "title": "资源明细：【$EPS】【$hostIP】【$hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "时延",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_latency{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-时延"
    }
   ]
  },
  {
   "title": "丢包率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_packet_loss_rate{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-丢包率"
    }
   ]
  },
  {
   "title": "网络(流入/流出)带宽",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "binbps", "label": "网络流入带宽（+）/网络流出带宽（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_bits_rate{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流入带宽"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_bits_rate{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流出带宽"
    }
   ]
  },
  {
   "title": "网络(流入/流出)流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "网络流入流量（+）/网络流出流量（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_bytes{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流入流量"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_bytes{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流出流量"
    }
   ]
  },
  {
   "title": "网络(流入/流出)包速率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "cps", "label": "网络流入包速率（+）/网络流出包速率（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_packets_rate{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流入包速率"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_packets_rate{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流出包速率"
    }
   ]
  },
  {
   "title": "网络(流入/流出)包量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "网络流入包量（+）/网络流出包量（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_packets{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流入包量"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_packets{device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{device_id}}({{name}})-网络流出包量"
    }
   ]
  }
 ]
}