{
 "title": "文档数据库服务(DDS)",
 "description": "【文档数据库服务监控指标说明】https://support.huaweicloud.com/usermanual-dds/dds_03_0026.html",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "DDS资源总览表【企业项目：$EPS】",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_dds_mongo031_cpu_usage{epId=~\"$EPS\"}) by (name)",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "avg(huaweicloud_sys_dds_mongo032_mem_usage{epId=~\"$EPS\"}) by (name)",
     "legendFormat": "入网使用率"
    },
    {
     "expr": "avg(huaweicloud_sys_dds_mongo035_disk_usage{epId=~\"$EPS\"}) by (name)",
     "legendFormat": "入网流量"
    },
    {
     "expr": "avg(huaweicloud_sys_dds_mongo007_connections_usage{epId=~\"$EPS\"}) by (name)",
     "legendFormat": "出网带宽"
    }
   ]
  },
  {
   "title": "insert语句执行频率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo003_insert_ps{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "query语句执行频率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo004_query_ps{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "主节点的Oplog中可用时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo025_repl_oplog_win{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "主节点生成Oplog的速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mb/hour" } },
   "yaxes": [
    { "format": "mb/hour" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo026_oplog_size_ph{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "主备Oplog重叠时长",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo025_repl_headroom{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "主备延时",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dds_mongo026_repl_lag{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}