{
 "title": "分布式消息服务(Kafka)",
 "description": "【文档数据库服务监控指标说明】https://support.huaweicloud.com/usermanual-dds/dds_03_0026.html",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "实例资源总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "实例级资源总览表【企业项目：$EPS】",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_dms_current_partitions{epId=~\"$EPS\"}) by(kafka_instance_id)",
     "legendFormat": "分区数"
    },
    {
     "expr": "avg(huaweicloud_sys_dms_current_topics{epId=~\"$EPS\"}) by(kafka_instance_id)",
     "legendFormat": "主题数"
    },
    {
     "expr": "avg(huaweicloud_sys_dms_group_msgs{epId=~\"$EPS\"}) by (kafka_instance_id)",
     "legendFormat": "消息堆积数"
    }
   ]
  },
  { "title": "Broker监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_cpu_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}>{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_memory_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}>{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_disk_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}>{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "消费流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_out_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}>{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "生产流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_in_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}>{{kafka_broker}}"
    }
   ]
  },
  { "title": "Topic监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "队列数据容量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_data_size{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}>{{kafka_topics}}"
    }
   ]
  },
  {
   "title": "消息生产速率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_messages_in_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}>{{kafka_topics}}"
    }
   ]
  }
 ]
}