{
 "title": "分布式消息服务RabbitMQ",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "内存高水位状态",
   "type": "stat",
   "description": "表示rabbitmq节点是否出发内存高水位，如果出发会阻塞集群的所有生产者",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_memory_high_watermark",
     "legendFormat": "{{instanceName}},{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "磁盘高水位状态",
   "type": "stat",
   "description": "表示rabbitmq节点是否触发磁盘高水位，如果触发会阻塞集群的所有生产者",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_disk_insufficient",
     "legendFormat": "{{instanceName}},{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "节点存活状态",
   "type": "stat",
   "description": "表示rabbitmq节点是否存活",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_alive",
     "legendFormat": "{{instanceName}},{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_cpu_usage",
     "legendFormat": "{{instanceName}},{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_memory_usage",
     "legendFormat": "{{instanceName}},{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "可消费消息数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_messages_ready",
     "legendFormat": "{{instanceName}}"
    }
   ]
  },
  {
   "title": "未确认消息数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_messages_unacknowledged",
     "legendFormat": "{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_connections",
     "legendFormat": "{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例通道数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "huaweicloud_sys_dms_channels", "legendFormat": "{{instanceName}}" }
   ]
  },
  {
   "title": "通道进程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_proc_used",
     "legendFormat": "{{instanceName}},{{rabbitmq_node}}"
    }
   ]
  }
 ]
}