{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "instanceName",
    "label": "云手机实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_ecp_cpu_util{epId=~\"$EPS\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "弹性云手机监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "指标概览",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_cpu_util{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_disk_read_bytes_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_disk_write_bytes_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_disk_read_requests_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_disk_write_requests_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_incoming_bytes_aggregate_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_outgoing_bytes_aggregate_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_vm_connections{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_vm_bandwidth_in{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_vm_bandwidth_out{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_vm_pps_in{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_vm_pps_out{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_ecp_network_vm_newconnections{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_cpu_util{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "磁盘读带宽",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_disk_read_bytes_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "磁盘写带宽",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_disk_write_bytes_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "磁盘读IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_disk_read_requests_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "磁盘写IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_disk_write_requests_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "带外网络流入速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_incoming_bytes_aggregate_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "带外网络流出速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_outgoing_bytes_aggregate_rate{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "网络连接数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_vm_connections{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "实例入方向带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_vm_bandwidth_in{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "实例出方向带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_vm_bandwidth_out{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "实例入方向PPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_vm_pps_in{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "实例出方向PPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_vm_pps_out{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  },
  {
   "title": "实例整机新建连接数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ecp_network_vm_newconnections{instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
     "legendFormat": "实例名称: {{name}}"
    }
   ]
  }
 ]
}