{
 "title": "弹性负载均衡(ELB)",
 "description": "【华为云ELB监控指标说明】https://support.huaweicloud.com/usermanual-elb/elb_ug_jk_0001.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "ELB-IP",
    "query": {
     "query": "label_values(huaweicloud_sys_elb_m2_act_conn{epId=~\"$EPS\"},vip_address)"
    }
   },
   {
    "name": "hostname",
    "label": "实例名",
    "query": {
     "query": "label_values(huaweicloud_sys_elb_m2_act_conn{epId=~\"$EPS\",vip_address=~\"$hostIP\"},name)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_agt_ecs_net_tcp_established{epId=~\"$EPS\"}))"
    }
   },
   {
    "name": "listener",
    "label": "监听器",
    "query": {
     "query": "label_values(huaweicloud_sys_elb_m2_act_conn{name=~\"$hostname\", vip_address=~\"$hostIP\"},listener_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源总览（企业项目）企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "ELB资源总览表【企业项目：$EPS】",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m1_cps{epId=~\"$EPS\"} -0",
     "legendFormat": "并发连接数"
    },
    {
     "expr": "huaweicloud_sys_elb_m2_act_conn{epId=~\"$EPS\"} - 0",
     "legendFormat": "活跃连接数"
    },
    {
     "expr": "huaweicloud_sys_elb_m3_inact_conn{epId=~\"$EPS\"} - 0",
     "legendFormat": "非活跃连接数"
    },
    {
     "expr": "huaweicloud_sys_elb_m4_ncps{epId=~\"$EPS\"} - 0",
     "legendFormat": "新建连接数"
    },
    {
     "expr": "avg(huaweicloud_sys_elb_m7_in_Bps{epId=~\"$EPS\"}) by (listener_name)",
     "legendFormat": "网络流入速率"
    },
    {
     "expr": "avg(huaweicloud_sys_elb_m8_out_Bps{epId=~\"$EPS\"}) by (listener_name)",
     "legendFormat": "网络流出速率"
    },
    {
     "expr": "avg(huaweicloud_sys_elb_m15_l7_upstream_4xx{epId=~\"$EPS\"}) by (listener_name)",
     "legendFormat": "7层后端返回码(4XX)"
    },
    {
     "expr": "avg(huaweicloud_sys_elb_m16_l7_upstream_5xx{epId=~\"$EPS\"}) by (listener_name)",
     "legendFormat": "7层后端返回码(5XX)"
    }
   ]
  },
  {
   "title": "资源明细：【$EPS】【$hostIP】【$hostname】【$listener】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "EPS"
  },
  {
   "title": "活跃连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m2_act_conn{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-活跃连接数"
    }
   ]
  },
  {
   "title": "非活跃连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m3_inact_conn{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-非活跃连接数"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m1_cps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-并发连接数"
    }
   ]
  },
  {
   "title": "并发连接使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_l4_con_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_L4并发连接数"
    },
    {
     "expr": "huaweicloud_sys_elb_l7_con_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_L7并发连接数"
    }
   ]
  },
  {
   "title": "新建连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m4_ncps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-新建连接数"
    }
   ]
  },
  {
   "title": "新建连接使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_l4_ncps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_L4新建连接数"
    },
    {
     "expr": "huaweicloud_sys_elb_l7_ncps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_L7新建连接数"
    }
   ]
  },
  {
   "title": "网络流入/流出速率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m7_in_Bps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-网络流入速率"
    },
    {
     "expr": "0 - huaweicloud_sys_elb_m8_out_Bps{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-网络流出速率"
    }
   ]
  },
  {
   "title": "网络流入/流出带宽使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "percent", "label": "入带宽使用率（+）/出带宽使用率（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_l4_in_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_4层入带宽使用率"
    },
    {
     "expr": "0 - huaweicloud_sys_elb_l4_out_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_4层出带宽使用率"
    },
    {
     "expr": "huaweicloud_sys_elb_l7_in_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_7层入带宽使用率"
    },
    {
     "expr": "0 - huaweicloud_sys_elb_l7_out_bps_usage{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}_{{name}}_7层出带宽使用率"
    }
   ]
  },
  {
   "title": "正常主机数量",
   "type": "graph",
   "description": "\n\nWrite Requests: 每个磁盘分区每秒写完成次数",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_ma_normal_servers{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{pool_name}})-正常主机数"
    }
   ]
  },
  {
   "title": "异常主机数量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m9_abnormal_servers{vip_address=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{pool_name}})-异常主机数"
    }
   ]
  },
  {
   "title": "后端返回码4XX",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m15_l7_upstream_4xx{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-7层后端返回码(4XX)"
    }
   ]
  },
  {
   "title": "后端返回码5XX",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_elb_m16_l7_upstream_5xx{vip_address=~\"$hostIP\",name=~\"$hostname\",listener_name=~\"$listener\"}",
     "legendFormat": "{{vip_address}}({{name}}---{{listener_name}})-7层后端返回码(5XX)"
    }
   ]
  }
 ]
}