{
 "title": "云搜索服务(ES)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "clusterName",
    "label": "集群名称",
    "query": {
     "query": "label_values(huaweicloud_sys_es_task_cnt{epId=\"$EPS\"},name)"
    }
   },
   {
    "name": "instanceName",
    "label": "实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_es_jvm_heap_usage_percentage{name=\"$clusterName\"},instanceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "koosearch集群",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "文档解析任务执行成功数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_task_success_cnt{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "文档解析任务执行失败数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_task_fail_cnt{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "文档解析任务提交数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_task_cnt{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "文档解析任务排队数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_task_pending_cnt{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "文档解析任务最大耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 295 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_task_max_delay{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "文档解析任务平均耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 295 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_task_avg_delay{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "知识库总数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 303 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_knowledge_repo_cnt{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "集群所有知识库索引容量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 303 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_es_index_capacity{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "文件总数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 311 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_file_cnt{name=~\"$clusterName\", epId=~\"$EPS\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "koosearch实例",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用ocr智能文档解析时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_delay{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "调用ocr智能文档解析次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "调用ocr智能文档解析成功率",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_succ_rate{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "调用ocr智能文档解析1xx状态码次数",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_code_1xx{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "调用ocr智能文档解析2xx状态码次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_code_2xx{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "调用ocr智能文档解析3xx状态码次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_code_3xx{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "调用ocr智能文档解析4xx状态码次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_code_4xx{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "调用ocr智能文档解析5xx状态码次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_ocr_request_code_5xx{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_request_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "搜索次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_search_request_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-搜索规划平均时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_search_plan_avg_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-搜索平均时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_search_avg_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-首Token平均时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_first_letter_avg_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答调用平均总时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_avg_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-搜索最大时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_search_max_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-搜索规划最大时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_search_plan_max_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "搜索调用平均总时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_search_avg_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答调用最大总时延",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_max_cost{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-调用搜索规划失败次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_search_plan_fail_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-调用搜索失败次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_search_fail_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-调用大模型失败次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_llm_fail_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答-Token数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_token_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "搜索成功率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_search_success_rate{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "问答成功率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_answer_success_rate{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "CPU利用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_cpu_usage_percentage{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "磁盘利用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_disk_usage_percentage{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "JVM堆使用率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_jvm_heap_usage_percentage{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "JVM老年代总GC次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_jvm_old_generation_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "JVM老年代总GC时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_jvm_old_generation_time{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "JVM年轻代总GC次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_jvm_young_generation_cnt{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "JVM年轻代总GC时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_jvm_young_generation_time{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "可用内存空间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_memory_available_space{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "已用内存比例",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_memory_usage_percentage{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    },
    {
     "title": "已用内存空间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "huaweicloud_sys_es_memory_usage_space{name=~\"$clusterName\", epId=~\"$EPS\",instanceName=~\"$instanceName\"}",
       "legendFormat": "集群名称: {{name}}"
      }
     ]
    }
   ]
  }
 ]
}