{
 "title": "gaussDBV5",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "instanceName",
    "query": {
     "query": "label_values(huaweicloud_sys_gaussdbv5_rds005_instance_disk_used_size{epId=~\"$EPS\"},name)"
    }
   },
   {
    "name": "nodeName",
    "query": {
     "query": "label_values(huaweicloud_sys_gaussdbv5_rds001_cpu_util{name=~\"$instanceName\"},nodeName)"
    }
   },
   {
    "name": "pdbName",
    "query": {
     "query": "label_values(huaweicloud_sys_gaussdbv5_pdb016_database_size{name=~\"$instanceName\"},pdbName)"
    }
   },
   {
    "name": "componentId",
    "query": {
     "query": "label_values(huaweicloud_sys_gaussdbv5_pdb002_used_shared_memory{name=~\"$instanceName\", pdbName=\"$pdbName\"},gaussdbv5_pdb_component_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "实例",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "指标概览",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds005_instance_disk_used_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds006_instance_disk_total_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds007_instance_disk_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds035_buffer_hit_ratio{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds036_deadlocks{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds048_P80{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds049_P95{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "磁盘使用大小(GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds005_instance_disk_used_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称: {{name}}"
      }
     ]
    },
    {
     "title": "磁盘使用率(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 89 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds007_instance_disk_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称: {{name}}"
      }
     ]
    },
    {
     "title": "实例数据磁盘总大小(GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 89 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds006_instance_disk_total_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称: {{name}}"
      }
     ]
    },
    {
     "title": "buffer命中率(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds035_buffer_hit_ratio{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称: {{name}}"
      }
     ]
    },
    {
     "title": "死锁数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds036_deadlocks{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称: {{name}}"
      }
     ]
    },
    {
     "title": "80% SQL的响应时间(us)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds048_P80{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称: {{name}}"
      }
     ]
    },
    {
     "title": "95% SQL的响应时间(us)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds049_P95{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", epId=~\"$EPS\"}",
       "legendFormat": "实例名称: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "节点",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU使用率(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds001_cpu_util{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "内存使用率(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds002_mem_util{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "数据写入量(Mib/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds003_bytes_in{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "数据传出量(Mib/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 239 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds004_bytes_out{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "数据磁盘每秒读写次数(Count/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 247 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds014_iops{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "数据磁盘写吞吐量(Byte/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 255 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds016_disk_write_throughput{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "数据磁盘读吞吐量(Byte/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 255 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds017_disk_read_throughput{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "数据磁盘单次写入花费的时间(ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 263 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds020_avg_disk_ms_per_write{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "数据磁盘单次读取花费的时间(ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 263 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds021_avg_disk_ms_per_read{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "磁盘 io 带宽占用率(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 271 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_io_bandwidth_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "IOPS 使用率(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 271 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_iops_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "交换内存使用率(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 279 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds068_swap_used_ratio{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "交换内存总大小(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 279 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds069_swap_total_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "系统数据库大小(Byte)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds084_sys_database_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "用户数据库总大小(Byte)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 287 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_rds085_user_database_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "重传比例(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 295 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_retrans_rate{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "用户态CPU时间占比(%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 303 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_cpu_user_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "内核态CPU时间占比(%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 9, "y": 303 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_cpu_sys_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    },
    {
     "title": "硬盘IO等待时间占比(%)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 303 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_cpu_wait_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", nodeName=~\"$nodeName\"}",
       "legendFormat": "节点名称: {{nodeName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "pdb指标概览",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 224 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb016_database_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb017_disk_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PDB库大小",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb016_database_size{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\"}",
       "legendFormat": "pdbName: {{pdbName}}"
      }
     ]
    },
    {
     "title": "PDB磁盘使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb017_disk_usage{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\"}",
       "legendFormat": "pdbName: {{pdbName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "组件",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "动态内存使用量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb001_used_dynamic_memory{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "共享缓存使用量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb002_used_shared_memory{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "CPU 使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb003_avg_cpu_utilization{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "在线会话率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb031_online_ratio{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "在线会话数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb030_online_session{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "活跃会话数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb032_active_session{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "活跃会话率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb033_active_ratio{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "锁等待状态会话数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb034_wait_session{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "锁等待状态会话比率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb035_wait_ratio{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "buffer 命中率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb040_buffer_hit_ratio{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "80% SQL的响应时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb042_gauss_p80{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "95% SQL的响应时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb043_gauss_p95{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "Data Definition Language",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb055_ddl_count{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "Data Manipulation Language",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb056_dml_count{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "Data Control Language",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb057_dcl_count{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "用户提交事务数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb044_commit_counter{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "用户回滚事务数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb045_rollback_counter{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "后台提交事务数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb046_bg_commit_counter{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    },
    {
     "title": "用户事务平均响应时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "huaweicloud_sys_gaussdbv5_pdb048_resp_avg{gaussdbv5_instance_id=~\".+\", name=~\"$instanceName\", pdbName=~\"$pdbName\", gaussdbv5_pdb_component_id=~\"$componentId\"}",
       "legendFormat": "组件Id: {{componentId}}"
      }
     ]
    }
   ]
  }
 ]
}