{
 "title": "Cassandra监控看板",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "实例总览【企业项目: $EPS】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "Cassandra节点总览",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_nosql_nosql006_disk_total_size{epId=~\"$EPS\"}) by(cassandra_cluster_id,cassandra_node_id,instanceName,nodeName,nodePrivateIP)",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    },
    {
     "expr": "avg(huaweicloud_sys_nosql_cassandra001_cpu_usage{epId=~\"$EPS\"}) by(cassandra_cluster_id,cassandra_node_id,instanceName,nodeName,nodePrivateIP)",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    },
    {
     "expr": "avg(huaweicloud_sys_nosql_cassandra002_mem_usage{epId=~\"$EPS\"}) by(cassandra_cluster_id,cassandra_node_id,instanceName,nodeName,nodePrivateIP)",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  { "title": "节点基础监控【企业项目: $EPS】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "EPS" },
  {
   "title": "CPU使用率 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra001_cpu_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra002_mem_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{inistanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "存储容量使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_nosql007_disk_used_size{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "存储容量使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_nosql005_disk_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "最大读时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra167_read_max_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "读耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra015_read_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "最大写时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra166_write_max_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "写耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra016_write_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "读丢弃次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra052_dropped_read{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "写丢弃次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra049_dropped_mutation{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "挂起的读任务数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra038_pending_read{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "挂起的写任务数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra037_pending_write{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "网络输入吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra004_bytes_in{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "网络输出吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra003_bytes_out{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "活动连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra014_connections{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  { "title": "P95,P99,P999指标【企业项目: $EPS】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }, "repeat": "EPS" },
  {
   "title": "P95读时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra101_read_p95_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "P95写时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra096_write_p95_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "P99读时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra102_read_p99_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "P99写时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra097_write_p99_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "p999读时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra164_read_p999_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "p999写时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra163_write_p999_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "p99range读时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra107_range_slice_p99_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  },
  {
   "title": "p95range读时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_cassandra106_range_slice_p95_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}},{{nodeName}}"
    }
   ]
  }
 ]
}