{
 "title": "NoSQL",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tableName",
    "label": "DynamoTable名称",
    "query": {
     "query": "label_values(huaweicloud_sys_nosql_ddb001_read_units,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DynamoTable", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "写入单位",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb002_write_units{ddb_table_id=~\".+\", name=~\"$tableName\"}   ",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "读取单位",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb001_read_units{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "get请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb010_get_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "batch get请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb011_batch_get_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "query请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb012_query_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "scan请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb013_scan_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "put请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb014_put_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "batch write请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb015_batch_write_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "update请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb016_update_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "delete请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb017_delete_count{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均get时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb020_get_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小get时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb021_get_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大get时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb022_get_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均batch get时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb023_batch_get_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小batch get时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb024_batch_get_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大batch get时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb025_batch_get_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均query时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb026_query_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小query时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb027_query_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大query时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb028_query_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均scan时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb029_scan_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小scan时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb030_scan_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大scan时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb031_scan_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均put时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb032_put_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小put时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb033_put_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大put时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb034_put_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均batch write时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb035_batch_write_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小batch write时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb036_batch_write_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大batch write时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb037_batch_write_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均update时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb038_update_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小update时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb039_update_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大update时延",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb040_update_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "平均delete时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb041_delete_latency_mean{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最小delete时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb042_delete_latency_min{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  },
  {
   "title": "最大delete时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_ddb043_delete_latency_max{ddb_table_id=~\".+\", name=~\"$tableName\"}",
     "legendFormat": "名称: {{name}}"
    }
   ]
  }
 ]
}