{
 "title": "Web应用防火墙(WAF)",
 "description": "【华为云WAF监控指标说明】https://support.huaweicloud.com/usermanual-waf/waf_01_0372.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "waf_name",
    "label": "防护域名",
    "query": {
     "query": "label_values(huaweicloud_sys_waf_requests{},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源明细：【$waf_name】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "请求量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_requests{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-请求量"
    }
   ]
  },
  {
   "title": "入网总流量/出网总流量（5min）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "mbytes", "label": "入网总流量（+）/出网总流量（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_inbound_traffic{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-入网总流量(5min)"
    },
    {
     "expr": "0 - huaweicloud_sys_waf_outbound_traffic{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-出网总流量(5min)"
    }
   ]
  },
  {
   "title": "入网流量/出网流量(均值+峰值)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Mibits", "label": "入网流量（+）/出网流量（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_inbound_traffic_peak{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-入网流量的峰值(5min)"
    },
    {
     "expr": "0 - huaweicloud_sys_waf_outbound_traffic_peak{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-出网流量的峰值(5min)"
    },
    {
     "expr": "huaweicloud_sys_waf_inbound_traffic_mean{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-入网流量的均值(5min)"
    },
    {
     "expr": "0 - huaweicloud_sys_waf_outbound_traffic_mean{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-出网流量的均值(5min)"
    }
   ]
  },
  {
   "title": "WAF返回码2XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_waf_http_2xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF返回码（2XX）"
    }
   ]
  },
  {
   "title": "WAF返回码3XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_waf_http_3xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF返回码（3XX）"
    }
   ]
  },
  {
   "title": "WAF返回码4XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_waf_http_4xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF返回码（4XX）"
    }
   ]
  },
  {
   "title": "WAF返回码5XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_waf_http_5xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF返回码（5XX）"
    }
   ]
  },
  {
   "title": "QPS峰值",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_qps_peak{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-QPS峰值"
    }
   ]
  },
  {
   "title": "QPS均值",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_qps_mean{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-QPS均值"
    }
   ]
  }
 ]
}