apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudeye-exporter.fullname" . }}
  labels:
    {{- include "cloudeye-exporter.labels" . | nindent 4 }}
data:
  clouds.yml: >
  {{ .Values.config | nindent 4 }}

