apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudeye-exporter.fullname" . }}
  labels:
    {{- include "cloudeye-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudeye-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudeye-exporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cloudeye-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - args:
          - -config=/app/clouds.yml
          {{- if .Values.debug }}
          - -debug
          {{- end }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8087
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: cloud-config
              mountPath: /app/clouds.yml
              subPath: clouds.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime 
        - name: cloud-config
          configMap:
            name: {{ include "cloudeye-exporter.fullname" . }}
